ci: fail jobs if coverage requirements are not met

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,10 +33,8 @@ jobs:
       # if jacoco report doesn't exist, we can't go further
       - name: Verify coverage report existence and stop if missing
         run: |
-          pwd
-          ls          
           if [ ! -f "./target/site/jacoco/jacoco.xml" ]; then          
-           echo "Error: File 'back/target/site/jacoco/jacoco.xml' not found. Stopping pipeline."
+           echo "Error: File 'back/target/site/jacoco/jacoco.xml' not found. Job failed."
            exit 1
           fi
         shell: bash
@@ -74,6 +72,13 @@ jobs:
             -Dsonar.projectKey=wilzwert_BobApp_backend
             -Dproject.settings=./sonar-project-backend.properties
 
+      # fail job if requirements not met
+      - name: Fail job if needed
+        if: steps.run-tests.outcome == 'failure'
+        run: |
+          echo "Job failed : coverage checks have not been met. See step 'Run tests and generate coverage report' output, and coverage report"
+          exit 1
+
   frontend:
     runs-on: ubuntu-latest
     defaults:
@@ -96,9 +101,20 @@ jobs:
         uses: browser-actions/setup-chrome@v1
        
       - name: Run tests with coverage
+        id: run-frontend-tests
         env:
           CHROME_BIN: ${{ steps.install-chrome.outputs.chrome-path }}
         run: npm test -- --code-coverage --watch=false --browsers=ChromeHeadlessCI
+        continue-on-error: true # some steps must be executed even in case on failure
+
+      # if coverage report doesn't exist, we can't go further
+      - name: Verify coverage report existence and stop if missing
+        run: |
+          if [ ! -f "./coverage/bobapp/lcov.info" ]; then          
+           echo "Error: File 'coverage/bobapp/lcov.info' not found. Job failed."
+           exit 1
+          fi
+        shell: bash
 
       - name: Upload frontend coverage report artifact
         uses: actions/upload-artifact@v4
@@ -122,6 +138,7 @@ jobs:
 
       # Run SonarQube analysis
       - name: SonarQube Scan
+        if: steps.run-frontend-tests.outcome == 'success'
         uses: SonarSource/sonarqube-scan-action@v4
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
@@ -130,3 +147,10 @@ jobs:
            -Dsonar.organization=wilzwert
            -Dsonar.projectKey=wilzwert_BobApp_frontend
            -Dproject.settings=./sonar-project-frontend.properties
+
+      # fail job if requirements not met
+      - name: Fail job if needed
+        if: steps.run-frontend-tests.outcome == 'failure'
+        run: |
+          echo "Job failed : coverage checks have not been met. See step 'Run tests with coverage' output, and coverage report"
+          exit 1
